---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: simple-python-app
        image: milisucevic/simple-python-app:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: flask-container