apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
  labels:
    app: flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer